import { FormSchema } from '@/types/form';

export const PRESET_TEMPLATES: Omit<FormSchema, 'id' | 'createdAt' | 'updatedAt'>[] = [
  {
    title: 'SBIT Hackathon 2026 — Team Registration & Survey',
    description: 'Welcome to the official registration portal. Fill in your team details and event preferences below.',
    status: 'published',
    theme: {
      primaryColor: '#6366f1',
      backgroundColor: '#0b0f19',
      cardBackground: '#151d30',
      textColor: '#f1f5f9',
      accentColor: '#818cf8',
      fontFamily: 'Outfit',
      borderRadius: 'rounded-xl',
      bannerImage: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1200&q=80',
      layoutMode: 'conversational',
    },
    fields: [
      {
        id: 'field_name',
        type: 'short_text',
        label: 'Full Name of Team Lead',
        placeholder: 'e.g. Alex Rivera',
        description: 'Please provide the name of the designated primary contact.',
        required: true,
        validation: { minLength: 3, maxLength: 60 },
      },
      {
        id: 'field_role',
        type: 'multiple_choice',
        label: 'Are you registering as a Solo Hacker or a Team?',
        description: 'Teams can have up to 4 members.',
        required: true,
        options: ['Solo Hacker', 'Team (2-4 Members)'],
      },
      {
        id: 'field_team_details',
        type: 'paragraph',
        label: 'Team Name & Member Emails',
        placeholder: 'Team ByteBusters: member1@domain.com, member2@domain.com...',
        description: 'List teammate names and college email IDs.',
        required: true,
        validation: { minLength: 5, maxLength: 500 },
      },
      {
        id: 'field_track',
        type: 'multiple_choice',
        label: 'Select your preferred Hackathon Track',
        description: 'You can choose your primary domain of focus.',
        required: true,
        options: [
          'Web & Cloud Systems (WEB-08 Form Builder)',
          'AI & Machine Learning Workflow',
          'FinTech & Decentralized Ledger',
          'Open Innovation & Social Impact',
        ],
      },
      {
        id: 'field_date',
        type: 'date',
        label: 'Preferred Check-in Date & Slot',
        description: 'Select the date when your team will arrive on campus.',
        required: true,
      },
      {
        id: 'field_experience_rating',
        type: 'rating',
        label: 'Rate your prior hackathon experience (1 - Beginner, 5 - Veteran)',
        description: 'Helps our mentors calibrate review rounds.',
        required: true,
        minRating: 1,
        maxRating: 5,
      },
      {
        id: 'field_resume',
        type: 'file_upload',
        label: 'Upload Team Lead Resume / Portfolio (PDF or ZIP)',
        description: 'Used for fast-track recruitment opportunities by sponsors.',
        required: false,
      },
    ],
    logicRules: [
      {
        id: 'rule_solo_skip',
        title: 'Skip Team Details if Solo',
        sourceFieldId: 'field_role',
        condition: {
          fieldId: 'field_role',
          operator: 'equals',
          value: 'Solo Hacker',
        },
        action: {
          type: 'jump_to',
          targetFieldId: 'field_track',
        },
        elseAction: {
          type: 'show',
          targetFieldId: 'field_team_details',
        },
      },
    ],
    webhooks: [
      {
        id: 'wh_discord_demo',
        name: 'Coders Club Discord Alerts',
        url: 'https://discord.com/api/webhooks/mock-endpoint-demo',
        enabled: false,
        event: 'on_submission',
      },
    ],
  },
  {
    title: 'CS & AI Club Workshop Feedback & NPS',
    description: 'Help us improve future masterclasses by rating today’s hands-on machine learning session.',
    status: 'published',
    theme: {
      primaryColor: '#10b981',
      backgroundColor: '#0c1612',
      cardBackground: '#13241d',
      textColor: '#ecfdf5',
      accentColor: '#34d399',
      fontFamily: 'Inter',
      borderRadius: 'rounded-xl',
      bannerImage: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=1200&q=80',
      layoutMode: 'conversational',
    },
    fields: [
      {
        id: 'fb_1',
        type: 'short_text',
        label: 'Your Name or College Roll Number (Optional)',
        placeholder: 'Anonymous or e.g. CS-2024-042',
        required: false,
      },
      {
        id: 'fb_2',
        type: 'multiple_choice',
        label: 'How did you find the workshop pacing?',
        required: true,
        options: ['Too fast', 'Just right', 'Too slow'],
      },
      {
        id: 'fb_3',
        type: 'rating',
        label: 'Overall Rating of the Speaker & Content',
        description: '1 is poor, 5 is outstanding.',
        required: true,
        minRating: 1,
        maxRating: 5,
      },
      {
        id: 'fb_4',
        type: 'paragraph',
        label: 'What topics would you like covered in the next session?',
        placeholder: 'e.g. LLM fine-tuning, Rust for WebAssembly, Next.js 16 internals...',
        required: false,
      },
    ],
    logicRules: [],
    webhooks: [],
  },
  {
    title: 'Campus Hack Night RSVP & Dietary Requirements',
    description: 'Reserve your spot, badge, and midnight refreshment box for the 24-hour campus hackathon.',
    status: 'draft',
    theme: {
      primaryColor: '#f59e0b',
      backgroundColor: '#18120a',
      cardBackground: '#261c0e',
      textColor: '#fef3c7',
      accentColor: '#fbbf24',
      fontFamily: 'Plus Jakarta Sans',
      borderRadius: 'rounded-2xl',
      layoutMode: 'single_page',
    },
    fields: [
      {
        id: 'rsvp_name',
        type: 'short_text',
        label: 'Full Name',
        placeholder: 'Student Name',
        required: true,
      },
      {
        id: 'rsvp_diet',
        type: 'multiple_choice',
        label: 'Dietary Preference for Midnight Snacks',
        required: true,
        options: ['Standard / Vegetarian', 'Non-Vegetarian', 'Vegan / Jain Diet'],
      },
      {
        id: 'rsvp_tshirt',
        type: 'multiple_choice',
        label: 'T-Shirt Size for Swag Kit',
        required: true,
        options: ['S', 'M', 'L', 'XL', '2XL'],
      },
      {
        id: 'rsvp_notes',
        type: 'paragraph',
        label: 'Special Accommodations or Power Strip Request',
        required: false,
      },
    ],
    logicRules: [],
    webhooks: [],
  },
];
